export default {
  ERROR_MESSAGE: 'ERROR_MESSAGE',

  TICKET_ROW_ITEM_ID: 'TICKET_ROW_ITEM_ID',
  TICKET_ROW_ITEM_SUBJECT: 'TICKET_ROW_ITEM_SUBJECT',
  TICKET_ROW_ITEM_DESCRIPTION: 'TICKET_ROW_ITEM_DESCRIPTION',
  TICKET_ROW_ITEM_CREATED_AT: 'TICKET_ROW_ITEM_CREATED_AT',
  TICKET_ROW_ITEM_STATUS_TAG: 'TICKET_ROW_ITEM_STATUS_TAG',
  TICKET_ROW_ITEM_ORG_ID: 'TICKET_ROW_ITEM_ORG_ID',
  TICKET_ROW_ITEM_GROUP_ID: 'TICKET_ROW_ITEM_GROUP_ID',
  TICKET_ROW_ITEM_SUBMITTER_ID: 'TICKET_ROW_ITEM_SUBMITTER_ID',
  TICKET_ROW_ITEM_ASSIGNEE_ID: 'TICKET_ROW_ITEM_ASSIGNEE_ID',
  TICKET_GO_BACK_BUTTON: 'TICKET_GO_BACK_BUTTON',
  TICKET_NAVIGATE_HOME_BUTTON: 'TICKET_NAVIGATE_HOME_BUTTON',

  STATUS_TAG: 'STATUS_TAG',

  TICKET_ITEM: 'TICKET_ITEM',
  TICKET_ITEM_ID: 'TICKET_ITEM_ID',
  TICKET_ITEM_SUBJECT_AND_DATE: 'TICKET_ITEM_SUBJECT_AND_DATE',
  TICKET_ITEM_TAGS: 'TICKET_ITEM_TAGS',

  TICKETS_LIST_RESULT_TEXT: 'TICKETS_LIST_RESULT_TEXT',
  TICKETS_LIST_EMPTY_MESSAGE: 'TICKETS_LIST_EMPTY_MESSAGE',

  PAGINATOR_PAGE: 'PAGINATOR_PAGE',

  LOADER: 'LOADER',
};
